#!/bin/bash

_user="$(who|awk 'NR==1 {print $1}')"

chromeinstall=$(mktemp -d)
cd $chromeinstall
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
rpm2cpio google-chrome-stable_current_x86_64.rpm | cpio -idmv
cp -r etc opt usr /

cp /usr/share/applications/google-chrome.desktop /home/$_user/Desktop
chmod +x /home/$_user/Desktop/google-chrome.desktop
chown $_user: /home/$_user/Desktop/google-chrome.desktop
echo ""

echo "Installation complete"
sleep 3
exit
