#!/bin/bash

_user="$(who|awk 'NR==1 {print $1}')"

echo "[1/3] Installing Virtualbox"
xbps-install -Sy virtualbox-ose virtualbox-ose-dkms virtualbox-ose-guest-dkms linux5.10-headers
sleep 2
echo ""

echo "[2/3] Installing extension pack"
virtualboxinstall=(mktemp -d)
cd virtualboxinstall
wget https://download.virtualbox.org/virtualbox/6.1.26/Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.26.vbox-extpack
sleep 2

echo "[3/3] User added to vboxusers group"
usermod -aG vboxusers $_user
sleep 2

echo "Installation complete"
sleep 3
