#!/bin/bash

echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time
echo "Time set to 60"
sleep 1

echo 60 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo "Interval set to 60"
sleep 1

echo 20 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo "Probes set to 20"
sleep 1
echo ""

echo "Settings saved"
read

