#!/bin/bash

sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=4\"/g' /etc/default/grub
echo "Updating GRUB.."
update-grub >/dev/null 2>&1
echo "Quiet boot disabled"
sleep 3
